### ISSUE TITLE
Responsive navbar on mobile is breaking.

### ISSUE THREAD

**Issue by chetaldrich** [chetaldrich/Dunmo#6]
![screen shot 2015-02-02 at 11 02 19 am](https://cloud.githubusercontent.com/assets/8320907/6004919/0f0ee022-aacc-11e4-8556-f8aa1a197375.png)

**Comment by jeremyjs** [comment]
I recommend turning it into an [eye icon](http://fortawesome.github.io/Font-Awesome/icon/eye/).

**Comment by jeremyjs** [comment]
This issue was moved to Dunmo/dunmo-prototype#11
